language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

os:
  - linux
  - osx

before_install:
  - go get -u -v github.com/mattn/goveralls

script:
  # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - |
    if [[ $(uname) == Darwin ]]; then
      # Last supported version for GOOS=386 is go1.14 in Darwin
      if [[ $(go version | awk '{print $3}') =~ ^go1\.(9|10|11|12|13|14)$ ]]; then
          GOARCH=386 go build
      fi
    else
        GOARCH=386 go build
    fi

  - $GOPATH/bin/goveralls -v -service=travis-ci
